language: c
before_install:
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ wily universe"
  - sudo apt-get update -qq
  - sudo apt-get install autoconf libsodium-dev check
  - autoconf --version
  - automake --version
  - ./autogen.sh
