language: c
sudo: false
cache:
  directories:
    - $HOME/.ccache
addons:
  apt:
    sources:
      - kubuntu-backports # to get CMake >= 2.8.12
    packages:
      - cmake
      - check
before_install:
  - PATH="/usr/lib/ccache:$PATH" # enable ccache
  - export LD_LIBRARY_PATH=$HOME/lib # custom libs (for execution)
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig # custom libs (for linking)
install: ci-scripts/setup
script: ci-scripts/run
