#!/bin/bash -x
set -e

# This is needed because Ubuntu precise (12.04 LTS) doesn't know libsodium yet
# and I don't wanna use wily (unstable) because CMake 3.3 is not needed (CMake
# 2.8.12 is enough).

SODIUM_URL=https://github.com/jedisct1/libsodium/releases/download/1.0.3/libsodium-1.0.3.tar.gz
cd `mktemp -d /tmp/install-libsodium-XXXX`
wget $SODIUM_URL
tar xf libsodium-*.tar.gz && cd libsodium-*
./configure && make && make check && sudo make install
sudo ldconfig
