#!/bin/sh -x
set -e
mkdir -p build/test
cd build/test
cmake ../..
make VERBOSE=1
if make test
then
	echo "'make test' exited with: $?"
	exit 0
else
	echo "'make test' exited with: $?"
	cat Testing//Temporary/LastTest.log
	exit 1
fi
