#!/bin/sh -x
set -e
mkdir -p build/test
cd build/test
cmake ../..
make VERBOSE=1
if ! make test
then
	echo "'make test' exited with: $?"
	cat test/c_round_trip.out || true
	cat test/c_round_trip.err || true
	exit 1
fi
